// Backblaze B2 transfer: turn ready items into paste-ready rclone commands.
// This app never moves bytes itself; it emits `rclone copyto gd: -> b2:`
// lines (run on Google Cloud Shell, which has free bandwidth) with
// deterministic object keys, so a media folder per title is created
// automatically. Unlike the original desktop tool, the generated setup
// script never embeds real B2 credentials or a Drive rclone remote — there
// is no secure place to hold either on a hosted server, so both are always
// left as placeholders for the operator to fill in locally.
const DRIVE_ROOT_ID = '11xi35nvqUqAHs4t911diIF0VZOZULlzd'
const SINEMAX_PREFIX = 'sinemax'

const ILLEGAL_SEG = /[\\/\x00-\x1f\x7f]/g

/** Sanitise one B2 key path segment (a folder or file name). */
function b2Seg(s: string | null | undefined): string {
  let out = (s || '').trim().replace(ILLEGAL_SEG, ' ')
  out = out.replace(/\s+/g, ' ').replace(/^[\s.]+|[\s.]+$/g, '')
  return out || 'untitled'
}

/**
 * 'DJ <name>' tag for a folder segment, or '' when no DJ is set.
 *
 * Auto-prepends 'DJ ' if the value doesn't already start with it, so 'Macky'
 * and 'DJ Macky' both render as 'DJ Macky'. This tag is what keeps two
 * variants of the same title (same title+year, different DJ) in separate B2
 * folders instead of overwriting each other.
 */
function djTag(dj: string | null | undefined): string {
  const trimmed = (dj || '').trim()
  if (!trimmed) return ''
  const seg = b2Seg(trimmed)
  return /^dj\b/i.test(seg) ? seg : `DJ ${seg}`
}

export type TransferTitle = {
  id: number
  raw_title: string | null
  matched_title: string | null
  type: string | null
  year: string | null
  dj: string | null
}

/**
 * Folder name for a title's media: 'Title (Year) - DJ Name'.
 *
 * Year and the DJ tag are both optional:
 *   'Knights (2025) - DJ Macky'  (full)
 *   'Knights (2025)'             (no DJ)
 *   'Knights - DJ Macky'         (no year)
 */
export function mediaFolder(t: TransferTitle): string {
  const title = b2Seg(t.matched_title || t.raw_title)
  const year = String(t.year || '').trim()
  const base = year ? `${title} (${year})` : title
  const dj = djTag(t.dj)
  return dj ? `${base} - ${dj}` : base
}

export type TransferAttachment = {
  id: number
  drive_name: string | null
  drive_path: string | null
}

/** Deterministic B2 key for one attached video file. */
export function videoObjectKey(t: TransferTitle, a: TransferAttachment): string {
  const kind = t.type === 'series' || t.type === 'tv' ? 'series' : 'movies'
  const fname = b2Seg(a.drive_name || `${a.id}.bin`)
  return `${SINEMAX_PREFIX}/${kind}/${mediaFolder(t)}/${fname}`
}

/** POSIX shell single-quoting, equivalent to Python's shlex.quote. */
function shQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`
}

export type TransferItem = {
  title: TransferTitle
  attachments: TransferAttachment[]
}

/**
 * Build (script, fileCount) of rclone copyto commands for the given items.
 * Each line copies one Drive file to its computed B2 key.
 */
export function buildTransferScript(
  items: TransferItem[],
  bucket = 'suacart'
): { script: string; total: number } {
  const lines = [
    '#!/usr/bin/env bash',
    '# Generated by Catalog Dashboard. Paste into Google Cloud Shell after the',
    '# one-time setup. Re-runnable: --ignore-existing skips files already in B2.',
    'set -uo pipefail',
    'set +m  # silence bash job-control [N] Done/PID spam when pasted directly',
    '# rclone lives in ~/bin (the only dir Cloud Shell persists); ensure PATH.',
    'export PATH="$HOME/bin:$PATH"',
    `BUCKET=b2:${bucket}`,
    '# How many files to transfer at once. Override before running, e.g.'
      + ' MAXJOBS=12 bash thisfile.sh',
    'MAXJOBS=${MAXJOBS:-8}',
    '# Each copy runs in the background; we block once MAXJOBS are in flight so'
      + ' several Drive->B2 hops overlap instead of going one-at-a-time.',
    'copy(){',
    '  while (( $(jobs -rp | wc -l) >= MAXJOBS )); do wait -n; done',
    '  { rclone copyto --ignore-existing --drive-stop-on-download-limit \\',
    '      --multi-thread-streams=4 --b2-chunk-size=100M \\',
    '      "gd:$1" "$BUCKET/$2" \\',
    '      && echo "  OK   $2" || echo "  FAIL $2"; } &',
    '}',
    '',
  ]

  let total = 0
  for (const { title: t, attachments } of items) {
    const label = (t.matched_title || t.raw_title || '').trim()
    lines.push(`# ${label} [${t.type || '?'}] -> media id ${t.id}`)
    if (attachments.length === 0) {
      lines.push('#   (no files attached)')
    }
    for (const a of attachments) {
      if (!a.drive_path) {
        lines.push(`#   SKIP (no drive_path): ${a.drive_name ?? ''}`)
        continue
      }
      lines.push(`copy ${shQuote(a.drive_path)} ${shQuote(videoObjectKey(t, a))}`)
      total += 1
    }
    lines.push('')
  }

  lines.push('wait  # let the last batch of background transfers finish')
  lines.push(`echo "Done. Files processed: ${total}"`)
  return { script: lines.join('\n'), total }
}

/**
 * One-time Cloud Shell setup: install rclone and write a config template.
 * Always placeholders for [gd] token and B2 keys — a hosted server has no
 * access to the operator's local rclone.conf or B2 secrets, and a
 * generated script is displayed in the browser, so real credentials must
 * never flow through it.
 */
export function buildSetupScript(): string {
  const conf = [
    '[gd]',
    'type = drive',
    'scope = drive.readonly',
    `root_folder_id = ${DRIVE_ROOT_ID}`,
    '',
    '[b2]',
    'type = b2',
    'account = YOUR_B2_KEY_ID',
    'key = YOUR_B2_APP_KEY',
  ].join('\n')

  const note = '# NOTE: paste your own [gd] token block below (rclone config reconnect gd:).\n'

  const install = [
    'mkdir -p "$HOME/bin"',
    'if [ ! -x "$HOME/bin/rclone" ]; then',
    '  echo "Installing rclone into ~/bin (persists across sessions)..."',
    '  tmp=$(mktemp -d)',
    '  curl -fsSL https://downloads.rclone.org/rclone-current-linux-amd64.zip'
      + ' -o "$tmp/rclone.zip"',
    '  unzip -q -o "$tmp/rclone.zip" -d "$tmp"',
    '  cp "$tmp"/rclone-*-linux-amd64/rclone "$HOME/bin/rclone"',
    '  chmod +x "$HOME/bin/rclone"',
    '  rm -rf "$tmp"',
    'fi',
    // Make sure interactive shells find it too (idempotent).
    'grep -q \'HOME/bin\' "$HOME/.bashrc" 2>/dev/null'
      + ' || echo \'export PATH="$HOME/bin:$PATH"\' >> "$HOME/.bashrc"',
    'export PATH="$HOME/bin:$PATH"',
    '',
  ].join('\n')

  return (
    '# ---- Google Cloud Shell: run ONCE (everything lives in your home dir) ----\n'
    + install
    + note
    + 'mkdir -p ~/.config/rclone\n'
    + "cat > ~/.config/rclone/rclone.conf <<'RCLONE_EOF'\n"
    + conf + '\n'
    + 'RCLONE_EOF\n'
    + '"$HOME/bin/rclone" version | head -1\n'
    + "echo 'Edit ~/.config/rclone/rclone.conf: paste your gd: token and real B2 account/key.'\n"
  )
}
